### ISSUE TITLE
When press install button (in Korean), the button keep pressed and the mouse cursor is the spinner, and it nothing happens

### ISSUE THREAD

**Issue by mdtrooper** [linuxmint/mintlocale#82]
The application shows:

![image](https://github.com/linuxmint/mintlocale/assets/1285451/ae5ed306-2ff9-4c40-a6a9-c48b577eadf7)

And my system is:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa
```

```
$ uname -a
Linux portatil 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ dpkg -l | grep mintlocale
ii  mintlocale                                                  1.5.9                                       all          Language selection tool
```

And when I try to execute as non-root user from the terminal this is the log when I click install:

```
$ mintlocale-im
/usr/lib/linuxmint/mintlocale/im.py:33: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/usr/lib/linuxmint/mintlocale/im.py:175: PyGIDeprecationWarning: GObject.idle_add is deprecated; use GLib.idle_add instead
  GObject.idle_add(self.check_input_methods_update_ui, currentIM, availableIM, allIM)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/defer/__init__.py", line 487, in _inline_callbacks
    result = gen.send(result)
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 1632, in _run_transaction_helper
    tid = dbus_method(*args, timeout=_APTDAEMON_DBUS_TIMEOUT)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintlocale/im.py", line 70, in install
    self.apt.update_cache()
  File "/usr/lib/python3/dist-packages/mintcommon/aptdaemon.py", line 38, in update_cache
    update_transaction = aptdaemon_client.update_cache()
  File "/usr/lib/python3/dist-packages/defer/utils.py", line 107, in _deferable
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/aptdaemon/errors.py", line 200, in _convert_dbus_exception
    raise get_native_exception(error)
  File "/usr/lib/python3/dist-packages/aptdaemon/errors.py", line 198, in _convert_dbus_exception
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 1500, in update_cache
    return self._run_transaction("UpdateCache", [], wait,
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 1608, in _run_transaction
    deferred.result.raise_exception()
  File "/usr/lib/python3/dist-packages/defer/__init__.py", line 130, in raise_exception
    raise self.value.with_traceback(self.traceback)
  File "/usr/lib/python3/dist-packages/defer/__init__.py", line 487, in _inline_callbacks
    result = gen.send(result)
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 1632, in _run_transaction_helper
    tid = dbus_method(*args, timeout=_APTDAEMON_DBUS_TIMEOUT)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Comment by mdtrooper** [comment]
Maybe there is the bug in `aptdaemon` because I was trying the code in python terminal and it fails (with similar log):

```
from aptdaemon import client
apt_client = client.AptClient()
apt_client.update_cache()

```

**Comment by mdtrooper** [comment]
And finally I tried with a root user, but it fails too.
